//! Build-time registry generation.
//!
//! A schema crate's `build.rs` calls [`generate_registry`]. It scans the crate's
//! own `src/` tree, finds every `#[wavedb]` struct, and writes
//! `$OUT_DIR/wavedb_registry.rs` — an `Object` enum (`STRUCT_HASH → variant`) with
//! static `from_wire` / `to_wire` / `struct_hash` dispatch, plus a `Registry`
//! value implementing [`wavedb_core::registry::ObjectRegistry`]. The schema crate
//! splices it in with `include!`.
//!
//! ```ignore
//! // build.rs
//! fn main() { wavedb_build::generate_registry(); }
//!
//! // lib.rs
//! include!(concat!(env!("OUT_DIR"), "/wavedb_registry.rs"));
//! ```
//!
//! **Scope: this crate's `src/` only.** The scanner reads source text — it does
//! not expand macros, evaluate `cfg`, or reach into dependencies. A `#[wavedb]`
//! struct from a dependency must be re-exported into `src/` to be registered. This
//! is the deliberate trade for filesystem auto-discovery.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use quote::quote;

mod scan;

pub use scan::ObjectEntry;

/// Scan `$CARGO_MANIFEST_DIR/src`, generate the registry, and write it to
/// `$OUT_DIR/wavedb_registry.rs`. Call this from a schema crate's `build.rs`.
///
/// # Panics
/// Panics with a clear message if the environment is missing (not a build script),
/// a source file fails to parse, or two `#[wavedb]` structs share a name.
pub fn generate_registry() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect(
        "CARGO_MANIFEST_DIR not set (generate_registry must run from build.rs)",
    );
    let out_dir = std::env::var("OUT_DIR")
        .expect("OUT_DIR not set (generate_registry must run from build.rs)");

    let src = Path::new(&manifest).join("src");
    println!("cargo:rerun-if-changed={}", src.display());

    let entries = scan::scan_dir(&src)
        .unwrap_or_else(|e| panic!("wavedb-build scan failed: {e}"));
    let code = render(&entries)
        .unwrap_or_else(|e| panic!("wavedb-build render failed: {e}"));

    let dest = Path::new(&out_dir).join("wavedb_registry.rs");
    fs::write(&dest, code).unwrap_or_else(|e| {
        panic!("wavedb-build: writing {}: {e}", dest.display())
    });
}

/// Render the generated registry module for `entries` as formatted Rust source.
///
/// # Errors
/// Returns an error if two entries share a variant name or the generated tokens
/// don't parse (an internal bug).
pub fn render(entries: &[ObjectEntry]) -> Result<String, String> {
    // Reject duplicate variant names — the `Object` enum can't carry two.
    let mut seen = BTreeSet::new();
    for e in entries {
        if !seen.insert(e.ident.clone()) {
            return Err(format!(
                "two #[wavedb] structs named `{}` — variant names must be unique \
                 across the schema crate",
                e.ident
            ));
        }
    }

    let variants = entries.iter().map(|e| {
        let ident = e.ident_token();
        let path = e.path_tokens();
        quote!(#ident(#path))
    });

    let struct_hash_arms = entries.iter().map(|e| {
        let ident = e.ident_token();
        let path = e.path_tokens();
        quote!(Object::#ident(_) => <#path>::STRUCT_HASH)
    });

    let from_wire_arms = entries.iter().map(|e| {
        let ident = e.ident_token();
        let path = e.path_tokens();
        quote!(h if h == <#path>::STRUCT_HASH =>
            ::core::result::Result::Ok(Object::#ident(::wavedb_core::from_wire(bytes)?)))
    });

    let to_wire_arms = entries.iter().map(|e| {
        let ident = e.ident_token();
        quote!(Object::#ident(v) => ::wavedb_core::to_wire(v))
    });

    let descriptor_arms = entries.iter().map(|e| {
        let path = e.path_tokens();
        quote!(h if h == <#path>::STRUCT_HASH =>
            ::core::option::Option::Some(&<#path>::OBJECT_DESCRIPTOR))
    });

    // Empty schema: an uninhabited enum still needs valid match bodies.
    let (struct_hash_body, to_wire_body) = if entries.is_empty() {
        (quote!(match *self {}), quote!(match *self {}))
    } else {
        (
            quote!(match self { #(#struct_hash_arms,)* }),
            quote!(match self { #(#to_wire_arms,)* }),
        )
    };

    // The generated module is machine-written and spliced into the user's crate;
    // silence style/lint noise and "unused" so it never pollutes their build.
    let allow = quote!(#[allow(clippy::all, clippy::pedantic, clippy::nursery, dead_code)]);

    let tokens = quote! {
        // @generated by wavedb-build — do not edit by hand.

        /// Every `#[wavedb]` struct declared in this crate, one variant per type.
        /// Intentionally underived so it imposes no bounds on the schema structs.
        #allow
        pub enum Object {
            #(#variants,)*
        }

        #allow
        impl Object {
            /// The `STRUCT_HASH` of the contained type.
            pub fn struct_hash(&self) -> u64 {
                #struct_hash_body
            }

            /// Parse `bytes` (a record body) into the variant for `struct_hash`.
            pub fn from_wire(struct_hash: u64, bytes: &[u8]) -> ::wavedb_core::Result<Object> {
                match struct_hash {
                    #(#from_wire_arms,)*
                    other => ::core::result::Result::Err(
                        ::wavedb_core::Error::UnknownStructHash(other)),
                }
            }

            /// Encode the contained record to wire bytes.
            pub fn to_wire(&self) -> ::std::vec::Vec<u8> {
                #to_wire_body
            }
        }

        /// The schema's static object registry.
        #allow
        #[derive(::core::fmt::Debug, ::core::clone::Clone, ::core::marker::Copy)]
        pub struct Registry;

        #allow
        impl ::wavedb_core::registry::ObjectRegistry for Registry {
            fn descriptor(
                &self,
                struct_hash: u64,
            ) -> ::core::option::Option<&'static ::wavedb_core::registry::ObjectDescriptor> {
                match struct_hash {
                    #(#descriptor_arms,)*
                    _ => ::core::option::Option::None,
                }
            }
        }

        /// The generated registry value, passed to a node's `Server`/`QuickNode`.
        #allow
        pub const REGISTRY: Registry = Registry;
    };

    // Format for readability; fall back to raw tokens if parsing the generated
    // text ever fails (would indicate a codegen bug, surfaced loudly).
    let file = syn::parse2::<syn::File>(tokens)
        .map_err(|e| format!("generated tokens did not parse: {e}"))?;
    let mut out = String::new();
    let _ = writeln!(out, "{}", prettyplease::unparse(&file));
    Ok(out)
}

/// Resolve the `src` directory under a manifest dir (test/helper convenience).
#[must_use]
pub fn src_dir(manifest_dir: &Path) -> PathBuf {
    manifest_dir.join("src")
}

#[cfg(test)]
mod tests {
    use super::{ObjectEntry, render};

    fn entry(path: &[&str], ident: &str) -> ObjectEntry {
        ObjectEntry {
            module_path: path.iter().map(|s| (*s).to_string()).collect(),
            ident: ident.to_string(),
        }
    }

    #[test]
    fn renders_variants_and_paths() {
        let code = render(&[
            entry(&[], "AboutUser"),
            entry(&["notes"], "Note"),
            entry(&["a", "b"], "Deep"),
        ])
        .unwrap();
        assert!(code.contains("AboutUser(crate::AboutUser)"));
        assert!(code.contains("Note(crate::notes::Note)"));
        assert!(code.contains("Deep(crate::a::b::Deep)"));
        assert!(code.contains("pub const REGISTRY: Registry = Registry;"));
        assert!(code.contains(
            "impl ::wavedb_core::registry::ObjectRegistry for Registry"
        ));
    }

    #[test]
    fn duplicate_variant_names_rejected() {
        let err =
            render(&[entry(&[], "Dup"), entry(&["x"], "Dup")]).unwrap_err();
        assert!(err.contains("Dup"));
    }

    #[test]
    fn empty_schema_is_valid_rust() {
        let code = render(&[]).unwrap();
        assert!(code.contains("pub enum Object"));
        assert!(code.contains("match *self {}"));
        // The generated text must still parse as a Rust file.
        syn::parse_file(&code).expect("empty registry parses");
    }
}
