//! Secondary-index codegen for `#[wavedb::pivot(...)]` declarations: the
//! `NonUniqueStruct` key hooks (`NUM_SECONDARIES` + `secondary_key`) and the
//! typed `by_<field>` lookup trait implemented for `Collection<T>`.
//!
//! Everything is static dispatch: `secondary_key` is a `match` over the
//! declared indexes, each `by_` method is a concrete trait method calling
//! `Collection::search_by` with its compile-time index number and the
//! `IndexKey` encoding of its field values.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{Ident, Type};

/// One resolved `#[wavedb::pivot(...)]`: the declared fields with their types.
pub struct ResolvedPivot {
    pub fields: Vec<(Ident, Type)>,
}

/// The borrowed parameter type a `by_` lookup takes for a field: `&str` for a
/// `String` field (the `IndexKey` encodings agree), `&T` otherwise.
fn param_ty(ty: &Type) -> TokenStream {
    if let Type::Path(p) = ty
        && p.path
            .segments
            .last()
            .is_some_and(|seg| seg.ident == "String")
    {
        return quote!(&str);
    }
    quote!(&#ty)
}

impl ResolvedPivot {
    /// The `IndexKey` expression encoding `self`'s field values — a direct
    /// field borrow for a single index, a ref-tuple for a composite.
    fn self_key_expr(&self) -> TokenStream {
        let refs = self.fields.iter().map(|(f, _)| quote!(&self.#f));
        if self.fields.len() == 1 {
            let f = &self.fields[0].0;
            quote!(::wavedb_core::IndexKey::key_bytes(&self.#f))
        } else {
            quote!(::wavedb_core::IndexKey::key_bytes(&(#(#refs),*)))
        }
    }

    /// The generated lookup's name: `by_f1` / `by_f1_f2`.
    fn by_ident(&self) -> Ident {
        let joined = self
            .fields
            .iter()
            .map(|(f, _)| f.to_string())
            .collect::<Vec<_>>()
            .join("_");
        format_ident!("by_{}", joined)
    }
}

/// The items injected into the `NonUniqueStruct` impl: the index count and the
/// per-index key encoder.
pub fn trait_items(specs: &[ResolvedPivot]) -> TokenStream {
    if specs.is_empty() {
        return TokenStream::new();
    }
    let n = specs.len();
    let arms = specs.iter().enumerate().map(|(i, spec)| {
        let expr = spec.self_key_expr();
        quote!(#i => #expr,)
    });
    quote! {
        const NUM_SECONDARIES: usize = #n;

        fn secondary_key(&self, index: usize) -> ::std::vec::Vec<u8> {
            match index {
                #(#arms)*
                _ => ::std::vec::Vec::new(),
            }
        }
    }
}

/// The `{Name}Secondaries` trait + its `Collection<{Name}>` impl: one typed
/// `by_<field>` lookup per declared index.
pub fn by_lookups(name: &Ident, specs: &[ResolvedPivot]) -> TokenStream {
    if specs.is_empty() {
        return TokenStream::new();
    }
    let trait_ident = format_ident!("{}Secondaries", name);

    let decls = specs.iter().map(|spec| {
        let by = spec.by_ident();
        let params = spec.fields.iter().map(|(f, ty)| {
            let ty = param_ty(ty);
            quote!(#f: #ty)
        });
        quote! {
            /// Stream the living records whose indexed field value(s) equal
            /// the given one(s), in index order — resolved two-phase
            /// (index → ids → fetch), like `all`.
            fn #by<'a, S: ::wavedb_core::Store>(
                &self,
                store: &'a S,
                #(#params),*
            ) -> impl ::wavedb_core::Stream<
                Item = ::wavedb_core::Result<(::wavedb_core::Id, #name)>,
            > + 'a;
        }
    });

    let impls = specs.iter().enumerate().map(|(i, spec)| {
        let by = spec.by_ident();
        let params = spec.fields.iter().map(|(f, ty)| {
            let ty = param_ty(ty);
            quote!(#f: #ty)
        });
        let names: Vec<&Ident> = spec.fields.iter().map(|(f, _)| f).collect();
        let key_expr = if names.len() == 1 {
            let f = names[0];
            quote!(::wavedb_core::IndexKey::key_bytes(#f))
        } else {
            quote!(::wavedb_core::IndexKey::key_bytes(&(#(#names),*)))
        };
        quote! {
            fn #by<'a, S: ::wavedb_core::Store>(
                &self,
                store: &'a S,
                #(#params),*
            ) -> impl ::wavedb_core::Stream<
                Item = ::wavedb_core::Result<(::wavedb_core::Id, #name)>,
            > + 'a {
                self.search_by(
                    store,
                    #i,
                    ::wavedb_core::Bound::Exact(#key_expr),
                )
            }
        }
    });

    quote! {
        /// Typed secondary-index lookups for this type's collection, one per
        /// `#[wavedb::pivot(...)]` (generated by `#[wavedb]`).
        pub trait #trait_ident {
            #(#decls)*
        }

        impl #trait_ident for ::wavedb_core::Collection<#name> {
            #(#impls)*
        }
    }
}
